/** Shared catalog metadata used by sync scripts (maps to former sell-catalog.ts). */

export const CATEGORY_HANDLE_BY_SLUG = {
  mobile: "mobile-phones",
  tablets: "tablets",
  "games-consoles": "games-consoles",
  "sell-my-watch": "smart-watches",
  "sell-my-camera": "cameras",
};

export const CATEGORIES = [
  {
    handle: "mobile-phones",
    title: "Mobile Phones",
    categorySlug: "mobile",
    tag: "category:mobile",
    sellHref: "/sell-my/mobile",
    buyHref: "/buy-used/mobile-phones",
    heroImage: "/images/category-brands-phones.jpeg",
    heading: "Trade in Your Mobile Phones",
    sellTitle: "Trade in Your Mobile Phones",
    buyTitle: "Refurbished Mobile Phones",
    layout: "brand-picker",
  },
  {
    handle: "tablets",
    title: "Tablets",
    categorySlug: "tablets",
    tag: "category:tablets",
    sellHref: "/sell-my/tablets",
    buyHref: "/buy-used/tablets",
    heroImage: "/images/MicrosoftTeams-image_6_.png",
    heading: "Trade-In Your Old Tablets",
    sellTitle: "Sell my Tablet",
    buyTitle: "Refurbished Tablets",
    layout: "catalog",
  },
  {
    handle: "games-consoles",
    title: "Games Consoles",
    categorySlug: "games-consoles",
    tag: "category:games-consoles",
    sellHref: "/sell-my/games-consoles",
    buyHref: "/buy-used/game-consoles",
    heroImage: "/images/Refurbished_Consoles_-_ps5.png",
    heading: "Trade-In Your Games Console",
    sellTitle: "Sell my Games Console",
    buyTitle: "Refurbished Games Consoles",
    layout: "catalog",
  },
  {
    handle: "smart-watches",
    title: "Smart Watches",
    categorySlug: "sell-my-watch",
    tag: "category:sell-my-watch",
    sellHref: "/sell-my/sell-my-watch",
    buyHref: "/buy-used/smart-watches",
    heroImage: "/images/MicrosoftTeams-image_7_.png",
    heading: "Trade-In Your Used Smart Watch",
    sellTitle: "Sell my Smartwatch",
    buyTitle: "Refurbished Smartwatches",
    layout: "catalog",
  },
  {
    handle: "cameras",
    title: "Cameras",
    categorySlug: "sell-my-camera",
    tag: "category:sell-my-camera",
    sellHref: "/sell-my/sell-my-camera",
    buyHref: "/buy-used/cameras",
    heroImage: "/images/Go_pro.png",
    heading: "Trade-In Your Used Camera",
    sellTitle: "Sell my Camera",
    buyTitle: "Refurbished Cameras",
    layout: "catalog",
  },
];

export const MOBILE_BRANDS = [
  { slug: "samsung", label: "Samsung", logo: "/images/brands/SAMSUNG_1_1.png", cardLabel: "Trade In Your Samsung Mobile Phone", heroImage: "/images/Mobile_Phones_-_Samsung_Child__1_2.png" },
  { slug: "apple", label: "Apple", logo: "/images/brands/APPLE.png", cardLabel: "Trade In Your iPhone" },
  { slug: "google", label: "Google", logo: "/images/brands/GOOGLE_PIXEL_1.png", cardLabel: "Trade In Your Google Pixel" },
  { slug: "huawei", label: "Huawei", logo: "/images/brands/HUAWEI.png", cardLabel: "Trade In Your Huawei Mobile Phone" },
  { slug: "honor", label: "Honor", logo: "/images/brands/HONOR.png", cardLabel: "Trade In Your Honor Mobile Phone" },
  { slug: "oppo", label: "Oppo", logo: "/images/brands/OPPO.png", cardLabel: "Trade In Your Oppo Mobile Phone" },
  { slug: "oneplus", label: "OnePlus", logo: "/images/brands/ONEPLUS.png", cardLabel: "Trade In Your OnePlus Mobile Phone" },
  { slug: "cat", label: "Cat", logo: "/images/brands/CAT.png", cardLabel: "Trade In Your Cat Mobile Phone" },
  { slug: "blackberry", label: "Blackberry", logo: "/images/brands/BLACKBERRY.png", cardLabel: "Trade In Your Blackberry Mobile Phone" },
  { slug: "htc", label: "HTC", logo: "/images/brands/HTC_1.png", cardLabel: "Trade In Your HTC Mobile Phone" },
  { slug: "lg", label: "LG", logo: "/images/brands/LG.png", cardLabel: "Trade In Your LG Mobile Phone" },
  { slug: "motorola", label: "Motorola", logo: "/images/brands/MOTOROLA.png", cardLabel: "Trade In Your Motorola Mobile Phone" },
  { slug: "nokia", label: "Nokia", logo: "/images/brands/NOKIA.png", cardLabel: "Trade In Your Nokia Mobile Phone" },
  { slug: "razer", label: "Razer", logo: "/images/brands/RAZER.png", cardLabel: "Trade In Your Razer Mobile Phone" },
  { slug: "realme", label: "Realme", logo: "/images/brands/REALME.png", cardLabel: "Trade In Your Realme Mobile Phone" },
  { slug: "redmi", label: "Redmi", logo: "/images/brands/REDMI.png", cardLabel: "Trade In Your Redmi Mobile Phone" },
  { slug: "sony", label: "Sony", logo: "/images/brands/SONY.png", cardLabel: "Trade In Your Sony Mobile Phone" },
  { slug: "xiaomi", label: "Xiaomi", logo: "/images/brands/XIAOMI.png", cardLabel: "Trade In Your Xiaomi Mobile Phone" },
  { slug: "zte", label: "ZTE", logo: "/images/brands/ZTE.png", cardLabel: "Trade In Your Zte Mobile Phone" },
  { slug: "hmd", label: "HMD", cardLabel: "Trade in Your HMD Mobile Phone" },
  { slug: "nothing", label: "Nothing", cardLabel: "Trade In Your Nothing Mobile Phone" },
];

export const SELL_MENU_ITEMS = CATEGORIES.map((c) => ({ title: c.title, url: c.sellHref }));

export const BUY_MENU_ITEMS = [
  { title: "Mobile Phones", url: "/buy-used/mobile-phones" },
  { title: "Tablets", url: "/buy-used/tablets" },
  { title: "Games Consoles", url: "/buy-used/game-consoles" },
  { title: "Smart Watches", url: "/buy-used/smart-watches" },
  { title: "Accessories", url: "/buy-used/accessories" },
  { title: "All Refurbished", url: "/buy-used/all-refurbished" },
  { title: "Big Deals", url: "/buy-used/deals" },
];
